name: Lint
on:
  push:
    paths-ignore:
      - 'resources/[base]/**.*'
  pull_request_target:
    paths-ignore: 
      - 'resources/[base]/**.*'
jobs:
  lint:
    name: Lint Resource
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Lint
        uses: Asaayu/fivem-lua-lint-action@master
        with:
          capture: "junit.xml"
          args: "-t --formatter JUnit"
          extra_libs: mysql+polyzone+undefinednatives+system
      - name: Generate Lint Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: "**/junit.xml"
          check_name: Linting Report
          fail_on_failure: false 
